### ISSUE TITLE
实例的set方法设置'date'时，时间无效（日期有效）

### ISSUE THREAD

**Issue by yusphy45** [youngerheart/daterangepicker#19]

**Comment by yusphy45** [comment]
code:
  var dateObj = new window.DateRangePicker(el, config);
  dateObj.set('date', window.moment('2015-11-25 10:33:00'));
result:
  display 2015-11-25 00:00

**Comment by youngerheart** [comment]
@yusphy45 fixed in #20 

``` php
$ bower install date-range-pickert || npm install date-range-picker@0.0.11 
```
