### ISSUE TITLE
date-terminal-picker 区间选择错误

### ISSUE THREAD

**Issue by coolzjy** [youngerheart/daterangepicker#21]
选择一个超过允许范围的区间（如限制为11-17，点击11-16进行选择），再选择其他区间（如点击11-6）时则产生错误
![qq20151117-0 2x](https://cloud.githubusercontent.com/assets/3762377/11206096/d7919d88-8d47-11e5-8889-74e97e810347.png)

**Comment by youngerheart** [comment]
fixed in #23
