### ISSUE TITLE
Demo page doesn't work

### ISSUE THREAD

**Issue by medikoo** [youngerheart/daterangepicker#64]
http://elemefe.github.io/daterangepicker/ crashes with errors on latest Chrome.
Technically nothing works

![screen shot 2016-07-05 at 09 32 17](https://cloud.githubusercontent.com/assets/122434/16577095/7adb17fc-4293-11e6-96c9-e5292150c469.png)

**Comment by youngerheart** [comment]
wow,but, in my chrome 51.0.2704.103, firefox 45.0.2 and safari it works well...

**Comment by medikoo** [comment]
It wasn't when I reported it, maybe it was some CDN issue.

Cannot reproduce it now, so closing it
